Fix date extraction for TraP_QC
Sometimes the date strings also have a microsecond value, causing the date not to be extracted correctly:

ValueError: unconverted data remains: .041702

This very small change just makes sure if this is ever the case, it is ignored and just the H M S is used.